### ISSUE TITLE
Urgent security issue!

### ISSUE THREAD

**Issue by tvlpirb** [grimreaperLinux/Archdotfiles#1]
I was going through your dotfiles and I noticed you included your Google Chrome and Brave folder, **please be careful** since all your browser history and logged in sessions can be viewed by others as all chrome user data is stored here. It can lead to compromise of personal data and of your accounts. This folder is highly sensitive and should not be shared. **Please remove this repository as soon as possible before someone malicious comes across it or alternatively read up on how to remove sensitive files from git.** In future, you can use a gitignore file so that these files do not get committed.

**Comment by grimreaperLinux** [comment]
I did that. Thank you for the warning.

**Comment by tvlpirb** [comment]
Your files are still there in commit history, this link may be useful [Removing sensitive data from a repository.](https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository)  Git keeps track of history including data that has been removed, you need to remove it from this history as well.

**Comment by grimreaperLinux** [comment]
I removed them with bfg. But i'm not able to verify if it's gone.

**Comment by grimreaperLinux** [comment]
Ah I'm making this repository private for now. I'm sorry but i'm too sleepy and I have
